#pragma once

#include "openwow/game/object_types.h"

#include <cstdint>

namespace openwow::game {

enum EObjectFields : std::uint16_t {
  OBJECT_FIELD_GUID    = 0x0000,
  OBJECT_FIELD_TYPE    = 0x0002,
  OBJECT_FIELD_ENTRY   = 0x0003,
  OBJECT_FIELD_SCALE_X = 0x0004,
  OBJECT_FIELD_PADDING = 0x0005,
  OBJECT_END           = 0x0006,
};

enum EItemFields : std::uint16_t {
  ITEM_FIELD_OWNER              = OBJECT_END + 0x0000,
  ITEM_FIELD_CONTAINED          = OBJECT_END + 0x0002,
  ITEM_FIELD_CREATOR            = OBJECT_END + 0x0004,
  ITEM_FIELD_GIFTCREATOR        = OBJECT_END + 0x0006,
  ITEM_FIELD_STACK_COUNT        = OBJECT_END + 0x0008,
  ITEM_FIELD_DURATION           = OBJECT_END + 0x0009,
  ITEM_FIELD_SPELL_CHARGES      = OBJECT_END + 0x000A,
  ITEM_FIELD_FLAGS              = OBJECT_END + 0x000F,
  ITEM_FIELD_ENCHANTMENT_1_1    = OBJECT_END + 0x0010,
  ITEM_FIELD_PROPERTY_SEED      = OBJECT_END + 0x0034,
  ITEM_FIELD_RANDOM_PROPERTIES_ID = OBJECT_END + 0x0035,
  ITEM_FIELD_DURABILITY         = OBJECT_END + 0x0036,
  ITEM_FIELD_MAXDURABILITY      = OBJECT_END + 0x0037,
  ITEM_FIELD_CREATE_PLAYED_TIME = OBJECT_END + 0x0038,
  ITEM_FIELD_PAD                = OBJECT_END + 0x0039,
  ITEM_END                      = OBJECT_END + 0x003A,
};

enum EContainerFields : std::uint16_t {
  CONTAINER_FIELD_NUM_SLOTS = ITEM_END + 0x0000,
  CONTAINER_ALIGN_PAD       = ITEM_END + 0x0001,
  CONTAINER_FIELD_SLOT_1    = ITEM_END + 0x0002,
  CONTAINER_END             = ITEM_END + 0x004A,
};

enum EUnitFields : std::uint16_t {
  UNIT_FIELD_CHARM                 = OBJECT_END + 0x0000,
  UNIT_FIELD_SUMMON                = OBJECT_END + 0x0002,
  UNIT_FIELD_CRITTER               = OBJECT_END + 0x0004,
  UNIT_FIELD_CHARMEDBY             = OBJECT_END + 0x0006,
  UNIT_FIELD_SUMMONEDBY            = OBJECT_END + 0x0008,
  UNIT_FIELD_CREATEDBY             = OBJECT_END + 0x000A,
  UNIT_FIELD_TARGET                = OBJECT_END + 0x000C,
  UNIT_FIELD_CHANNEL_OBJECT        = OBJECT_END + 0x000E,
  UNIT_CHANNEL_SPELL               = OBJECT_END + 0x0010,
  UNIT_FIELD_BYTES_0               = OBJECT_END + 0x0011,
  UNIT_FIELD_HEALTH                = OBJECT_END + 0x0012,
  UNIT_FIELD_POWER1                = OBJECT_END + 0x0013,
  UNIT_FIELD_POWER2                = OBJECT_END + 0x0014,
  UNIT_FIELD_POWER3                = OBJECT_END + 0x0015,
  UNIT_FIELD_POWER4                = OBJECT_END + 0x0016,
  UNIT_FIELD_POWER5                = OBJECT_END + 0x0017,
  UNIT_FIELD_POWER6                = OBJECT_END + 0x0018,
  UNIT_FIELD_POWER7                = OBJECT_END + 0x0019,
  UNIT_FIELD_MAXHEALTH             = OBJECT_END + 0x001A,
  UNIT_FIELD_MAXPOWER1             = OBJECT_END + 0x001B,
  UNIT_FIELD_MAXPOWER2             = OBJECT_END + 0x001C,
  UNIT_FIELD_MAXPOWER3             = OBJECT_END + 0x001D,
  UNIT_FIELD_MAXPOWER4             = OBJECT_END + 0x001E,
  UNIT_FIELD_MAXPOWER5             = OBJECT_END + 0x001F,
  UNIT_FIELD_MAXPOWER6             = OBJECT_END + 0x0020,
  UNIT_FIELD_MAXPOWER7             = OBJECT_END + 0x0021,
  UNIT_FIELD_POWER_REGEN_FLAT_MODIFIER   = OBJECT_END + 0x0022,
  UNIT_FIELD_POWER_REGEN_INTERRUPTED_FLAT_MODIFIER = OBJECT_END + 0x0029,
  UNIT_FIELD_LEVEL                 = OBJECT_END + 0x0030,
  UNIT_FIELD_FACTIONTEMPLATE       = OBJECT_END + 0x0031,
  UNIT_VIRTUAL_ITEM_SLOT_ID        = OBJECT_END + 0x0032,
  UNIT_FIELD_FLAGS                 = OBJECT_END + 0x0035,
  UNIT_FIELD_FLAGS_2               = OBJECT_END + 0x0036,
  UNIT_FIELD_AURASTATE             = OBJECT_END + 0x0037,
  UNIT_FIELD_BASEATTACKTIME        = OBJECT_END + 0x0038,
  UNIT_FIELD_RANGEDATTACKTIME      = OBJECT_END + 0x003A,
  UNIT_FIELD_BOUNDINGRADIUS        = OBJECT_END + 0x003B,
  UNIT_FIELD_COMBATREACH           = OBJECT_END + 0x003C,
  UNIT_FIELD_DISPLAYID             = OBJECT_END + 0x003D,
  UNIT_FIELD_NATIVEDISPLAYID       = OBJECT_END + 0x003E,
  UNIT_FIELD_MOUNTDISPLAYID        = OBJECT_END + 0x003F,
  UNIT_FIELD_MINDAMAGE             = OBJECT_END + 0x0040,
  UNIT_FIELD_MAXDAMAGE             = OBJECT_END + 0x0041,
  UNIT_FIELD_MINOFFHANDDAMAGE      = OBJECT_END + 0x0042,
  UNIT_FIELD_MAXOFFHANDDAMAGE      = OBJECT_END + 0x0043,
  UNIT_FIELD_BYTES_1               = OBJECT_END + 0x0044,
  UNIT_FIELD_PETNUMBER             = OBJECT_END + 0x0045,
  UNIT_FIELD_PET_NAME_TIMESTAMP    = OBJECT_END + 0x0046,
  UNIT_FIELD_PETEXPERIENCE         = OBJECT_END + 0x0047,
  UNIT_FIELD_PETNEXTLEVELEXP       = OBJECT_END + 0x0048,
  UNIT_DYNAMIC_FLAGS               = OBJECT_END + 0x0049,
  UNIT_MOD_CAST_SPEED              = OBJECT_END + 0x004A,
  UNIT_CREATED_BY_SPELL            = OBJECT_END + 0x004B,
  UNIT_NPC_FLAGS                   = OBJECT_END + 0x004C,
  UNIT_NPC_EMOTESTATE              = OBJECT_END + 0x004D,
  UNIT_FIELD_STAT0                 = OBJECT_END + 0x004E,
  UNIT_FIELD_STAT1                 = OBJECT_END + 0x004F,
  UNIT_FIELD_STAT2                 = OBJECT_END + 0x0050,
  UNIT_FIELD_STAT3                 = OBJECT_END + 0x0051,
  UNIT_FIELD_STAT4                 = OBJECT_END + 0x0052,
  UNIT_FIELD_POSSTAT0              = OBJECT_END + 0x0053,
  UNIT_FIELD_POSSTAT1              = OBJECT_END + 0x0054,
  UNIT_FIELD_POSSTAT2              = OBJECT_END + 0x0055,
  UNIT_FIELD_POSSTAT3              = OBJECT_END + 0x0056,
  UNIT_FIELD_POSSTAT4              = OBJECT_END + 0x0057,
  UNIT_FIELD_NEGSTAT0              = OBJECT_END + 0x0058,
  UNIT_FIELD_NEGSTAT1              = OBJECT_END + 0x0059,
  UNIT_FIELD_NEGSTAT2              = OBJECT_END + 0x005A,
  UNIT_FIELD_NEGSTAT3              = OBJECT_END + 0x005B,
  UNIT_FIELD_NEGSTAT4              = OBJECT_END + 0x005C,
  UNIT_FIELD_RESISTANCES           = OBJECT_END + 0x005D,
  UNIT_FIELD_RESISTANCEBUFFMODSPOSITIVE = OBJECT_END + 0x0064,
  UNIT_FIELD_RESISTANCEBUFFMODSNEGATIVE = OBJECT_END + 0x006B,
  UNIT_FIELD_BASE_MANA             = OBJECT_END + 0x0072,
  UNIT_FIELD_BASE_HEALTH           = OBJECT_END + 0x0073,
  UNIT_FIELD_BYTES_2               = OBJECT_END + 0x0074,
  UNIT_FIELD_ATTACK_POWER          = OBJECT_END + 0x0075,
  UNIT_FIELD_ATTACK_POWER_MODS     = OBJECT_END + 0x0076,
  UNIT_FIELD_ATTACK_POWER_MULTIPLIER = OBJECT_END + 0x0077,
  UNIT_FIELD_RANGED_ATTACK_POWER   = OBJECT_END + 0x0078,
  UNIT_FIELD_RANGED_ATTACK_POWER_MODS = OBJECT_END + 0x0079,
  UNIT_FIELD_RANGED_ATTACK_POWER_MULTIPLIER = OBJECT_END + 0x007A,
  UNIT_FIELD_MINRANGEDDAMAGE       = OBJECT_END + 0x007B,
  UNIT_FIELD_MAXRANGEDDAMAGE       = OBJECT_END + 0x007C,
  UNIT_FIELD_POWER_COST_MODIFIER   = OBJECT_END + 0x007D,
  UNIT_FIELD_POWER_COST_MULTIPLIER = OBJECT_END + 0x0084,
  UNIT_FIELD_MAXHEALTHMODIFIER     = OBJECT_END + 0x008B,
  UNIT_FIELD_HOVERHEIGHT           = OBJECT_END + 0x008C,
  UNIT_FIELD_PADDING_END           = OBJECT_END + 0x008D,
  UNIT_END                         = OBJECT_END + 0x008E,
};

enum EPlayerFields : std::uint16_t {
  PLAYER_DUEL_ARBITER              = UNIT_END + 0x0000,
  PLAYER_FLAGS                     = UNIT_END + 0x0002,
  PLAYER_GUILDID                   = UNIT_END + 0x0003,
  PLAYER_GUILDRANK                 = UNIT_END + 0x0004,
  PLAYER_BYTES                     = UNIT_END + 0x0005,
  PLAYER_BYTES_2                   = UNIT_END + 0x0006,
  PLAYER_BYTES_3                   = UNIT_END + 0x0007,
  PLAYER_DUEL_TEAM                 = UNIT_END + 0x0008,
  PLAYER_GUILD_TIMESTAMP           = UNIT_END + 0x0009,

  PLAYER_QUEST_LOG_1_1             = UNIT_END + 0x000A,

  PLAYER_VISIBLE_ITEM_1_ENTRYID    = UNIT_END + 0x0087,

  PLAYER_CHOSEN_TITLE              = UNIT_END + 0x00AD,
  PLAYER_FAKE_INEBRIATION          = UNIT_END + 0x00AE,

  PLAYER_FIELD_INV_SLOT_HEAD       = UNIT_END + 0x00B0,
  PLAYER_FIELD_PACK_SLOT_1         = UNIT_END + 0x00DE,
  PLAYER_FIELD_BANK_SLOT_1         = UNIT_END + 0x00FE,
  PLAYER_FIELD_BANKBAG_SLOT_1      = UNIT_END + 0x0136,
  PLAYER_FIELD_VENDORBUYBACK_SLOT_1= UNIT_END + 0x0144,
  PLAYER_FIELD_KEYRING_SLOT_1      = UNIT_END + 0x015C,
  PLAYER_FIELD_CURRENCYTOKEN_SLOT_1= UNIT_END + 0x019C,

  PLAYER_FARSIGHT                  = UNIT_END + 0x01DC,
  PLAYER_FIELD_KNOWN_TITLES        = UNIT_END + 0x01DE,
  PLAYER_FIELD_KNOWN_TITLES1       = UNIT_END + 0x01E0,
  PLAYER_FIELD_KNOWN_TITLES2       = UNIT_END + 0x01E2,
  PLAYER_FIELD_KNOWN_CURRENCIES    = UNIT_END + 0x01E4,

  PLAYER_XP                        = UNIT_END + 0x01E6,
  PLAYER_NEXT_LEVEL_XP             = UNIT_END + 0x01E7,

  PLAYER_SKILL_INFO_1_1            = UNIT_END + 0x01E8,

  PLAYER_CHARACTER_POINTS1         = UNIT_END + 0x0368,
  PLAYER_CHARACTER_POINTS2         = UNIT_END + 0x0369,

  PLAYER_TRACK_CREATURES           = UNIT_END + 0x036A,
  PLAYER_TRACK_RESOURCES           = UNIT_END + 0x036B,
  PLAYER_BLOCK_PERCENTAGE          = UNIT_END + 0x036C,
  PLAYER_DODGE_PERCENTAGE          = UNIT_END + 0x036D,
  PLAYER_PARRY_PERCENTAGE          = UNIT_END + 0x036E,
  PLAYER_EXPERTISE                 = UNIT_END + 0x036F,
  PLAYER_OFFHAND_EXPERTISE         = UNIT_END + 0x0370,
  PLAYER_CRIT_PERCENTAGE           = UNIT_END + 0x0371,
  PLAYER_RANGED_CRIT_PERCENTAGE    = UNIT_END + 0x0372,
  PLAYER_OFFHAND_CRIT_PERCENTAGE   = UNIT_END + 0x0373,
  PLAYER_SPELL_CRIT_PERCENTAGE1    = UNIT_END + 0x0374,
  PLAYER_SHIELD_BLOCK              = UNIT_END + 0x037B,

  PLAYER_EXPLORED_ZONES_1          = UNIT_END + 0x037D,

  PLAYER_REST_STATE_EXPERIENCE     = UNIT_END + 0x03FD,
  PLAYER_FIELD_COINAGE             = UNIT_END + 0x03FE,

  PLAYER_FIELD_MOD_DAMAGE_DONE_POS = UNIT_END + 0x03FF,
  PLAYER_FIELD_MOD_DAMAGE_DONE_NEG = UNIT_END + 0x0406,
  PLAYER_FIELD_MOD_DAMAGE_DONE_PCT = UNIT_END + 0x040D,
  PLAYER_FIELD_MOD_HEALING_DONE_POS= UNIT_END + 0x0414,
  PLAYER_FIELD_MOD_HEALING_PCT     = UNIT_END + 0x0415,
  PLAYER_FIELD_MOD_SPELL_POWER_PCT = UNIT_END + 0x0416,
  PLAYER_FIELD_MOD_TARGET_RESISTANCE     = UNIT_END + 0x0417,
  PLAYER_FIELD_MOD_TARGET_PHYSICAL_RESISTANCE = UNIT_END + 0x0418,
  PLAYER_FIELD_ACTION_BAR_TOGGLES = UNIT_END + 0x0419,

  PLAYER_AMMO_ID                   = UNIT_END + 0x041A,
  PLAYER_SELF_RES_SPELL            = UNIT_END + 0x041B,

  PLAYER_FIELD_BUYBACK_PRICE_1     = UNIT_END + 0x041D,
  PLAYER_FIELD_BUYBACK_TIMESTAMP_1 = UNIT_END + 0x0429,
  PLAYER_FIELD_KILLS               = UNIT_END + 0x0435,
  PLAYER_FIELD_TODAY_CONTRIBUTION  = UNIT_END + 0x0436,
  PLAYER_FIELD_YESTERDAY_CONTRIBUTION = UNIT_END + 0x0437,
  PLAYER_FIELD_LIFETIME_HONORABLE_KILLS = UNIT_END + 0x0438,
  PLAYER_FIELD_BYTES2              = UNIT_END + 0x0439,
  PLAYER_FIELD_WATCHED_FACTION_INDEX = UNIT_END + 0x043A,

  PLAYER_FIELD_COMBAT_RATING_1     = UNIT_END + 0x043B,
  PLAYER_FIELD_ARENA_TEAM_INFO_1_1 = UNIT_END + 0x0454,
  PLAYER_FIELD_HONOR_CURRENCY      = UNIT_END + 0x0469,
  PLAYER_FIELD_ARENA_CURRENCY      = UNIT_END + 0x046A,
  PLAYER_FIELD_MAX_LEVEL           = UNIT_END + 0x046B,
  PLAYER_FIELD_DAILY_QUESTS_1      = UNIT_END + 0x046C,

  PLAYER_RUNE_REGEN_1              = UNIT_END + 0x0485,
  PLAYER_NO_REAGENT_COST_1         = UNIT_END + 0x0489,
  PLAYER_FIELD_GLYPH_SLOTS_1       = UNIT_END + 0x048C,
  PLAYER_FIELD_GLYPHS_1            = UNIT_END + 0x0492,
  PLAYER_GLYPHS_ENABLED            = UNIT_END + 0x0498,
  PLAYER_PET_SPELL_POWER           = UNIT_END + 0x0499,

  PLAYER_END                       = UNIT_END + 0x049A,
};

enum EGameObjectFields : std::uint16_t {
  GAMEOBJECT_FIELD_CREATED_BY = OBJECT_END + 0x0000,
  GAMEOBJECT_DISPLAYID        = OBJECT_END + 0x0002,
  GAMEOBJECT_FLAGS            = OBJECT_END + 0x0003,
  GAMEOBJECT_PARENTROTATION   = OBJECT_END + 0x0004,
  GAMEOBJECT_DYNAMIC          = OBJECT_END + 0x0008,
  GAMEOBJECT_FACTION          = OBJECT_END + 0x0009,
  GAMEOBJECT_LEVEL            = OBJECT_END + 0x000A,
  GAMEOBJECT_BYTES_1          = OBJECT_END + 0x000B,
  GAMEOBJECT_END              = OBJECT_END + 0x000C,
};

enum EDynamicObjectFields : std::uint16_t {
  DYNAMICOBJECT_CASTER   = OBJECT_END + 0x0000,
  DYNAMICOBJECT_BYTES    = OBJECT_END + 0x0002,
  DYNAMICOBJECT_SPELLID  = OBJECT_END + 0x0003,
  DYNAMICOBJECT_RADIUS   = OBJECT_END + 0x0004,
  DYNAMICOBJECT_CASTTIME = OBJECT_END + 0x0005,
  DYNAMICOBJECT_END      = OBJECT_END + 0x0006,
};

enum ECorpseFields : std::uint16_t {
  CORPSE_FIELD_OWNER        = OBJECT_END + 0x0000,
  CORPSE_FIELD_PARTY        = OBJECT_END + 0x0002,
  CORPSE_FIELD_DISPLAY_ID   = OBJECT_END + 0x0004,
  CORPSE_FIELD_ITEM         = OBJECT_END + 0x0005,
  CORPSE_FIELD_BYTES_1      = OBJECT_END + 0x0018,
  CORPSE_FIELD_BYTES_2      = OBJECT_END + 0x0019,
  CORPSE_FIELD_GUILD        = OBJECT_END + 0x001A,
  CORPSE_FIELD_FLAGS        = OBJECT_END + 0x001B,
  CORPSE_FIELD_DYNAMIC_FLAGS= OBJECT_END + 0x001C,
  CORPSE_FIELD_PAD          = OBJECT_END + 0x001D,
  CORPSE_END                = OBJECT_END + 0x001E,
};

inline constexpr std::uint8_t kMaxValuesMaskBlocks = 42;

inline constexpr std::uint16_t PLAYER_OTHER_END = 324;

constexpr std::uint16_t FieldCountForPlayer(bool is_active_player) {
  return is_active_player ? PLAYER_END : PLAYER_OTHER_END;
}

constexpr std::uint16_t FieldCountFor(TypeID type) {
  switch (type) {
    case TypeID::kObject:        return OBJECT_END;
    case TypeID::kItem:          return ITEM_END;
    case TypeID::kContainer:     return CONTAINER_END;
    case TypeID::kUnit:          return UNIT_END;
    case TypeID::kPlayer:        return PLAYER_END;
    case TypeID::kGameObject:    return GAMEOBJECT_END;
    case TypeID::kDynamicObject: return DYNAMICOBJECT_END;
    case TypeID::kCorpse:        return CORPSE_END;
  }
  return OBJECT_END;
}

constexpr std::uint16_t FieldCountForOtherPlayer() {
  return PLAYER_OTHER_END;
}

template <typename FieldEnum, typename SectionEnum>
constexpr std::uint16_t DescriptorWordDistance(FieldEnum field,
                                               SectionEnum section_begin) {
  return static_cast<std::uint16_t>(static_cast<std::uint16_t>(field) -
                                    static_cast<std::uint16_t>(section_begin));
}

constexpr std::uint8_t BitmaskBlockCount(std::uint16_t field_count) {
  return static_cast<std::uint8_t>((field_count + 31) / 32);
}

}
