#include "openwow/ui/game/script_event_catalog.h"

#include "openwow/ui/game/game_events.h"

#include <limits>
#include <string_view>

namespace openwow::ui::game {

namespace {

constexpr std::string_view kRetailWorldEvents = R"(UNIT_PET

UNIT_PET

UNIT_TARGET

UNIT_DISPLAYPOWER
UNIT_HEALTH
UNIT_MANA
UNIT_RAGE
UNIT_FOCUS
UNIT_ENERGY
UNIT_HAPPINESS

UNIT_RUNIC_POWER
UNIT_MAXHEALTH
UNIT_MAXMANA
UNIT_MAXRAGE
UNIT_MAXFOCUS
UNIT_MAXENERGY
UNIT_MAXHAPPINESS

UNIT_MAXRUNIC_POWER

UNIT_LEVEL
UNIT_FACTION

UNIT_FLAGS
UNIT_FLAGS

UNIT_ATTACK_SPEED
UNIT_ATTACK_SPEED
UNIT_RANGEDDAMAGE

UNIT_DAMAGE
UNIT_DAMAGE
UNIT_DAMAGE
UNIT_DAMAGE

UNIT_PET_EXPERIENCE
UNIT_PET_EXPERIENCE
UNIT_DYNAMIC_FLAGS

UNIT_STATS
UNIT_STATS
UNIT_STATS
UNIT_STATS
UNIT_STATS

UNIT_RESISTANCES
UNIT_RESISTANCES
UNIT_RESISTANCES
UNIT_RESISTANCES
UNIT_RESISTANCES
UNIT_RESISTANCES
UNIT_RESISTANCES
UNIT_RESISTANCES
UNIT_RESISTANCES
UNIT_RESISTANCES
UNIT_RESISTANCES
UNIT_RESISTANCES
UNIT_RESISTANCES
UNIT_RESISTANCES
UNIT_RESISTANCES
UNIT_RESISTANCES
UNIT_RESISTANCES
UNIT_RESISTANCES
UNIT_RESISTANCES
UNIT_RESISTANCES
UNIT_RESISTANCES

UNIT_ATTACK_POWER
UNIT_ATTACK_POWER
UNIT_ATTACK_POWER
UNIT_RANGED_ATTACK_POWER
UNIT_RANGED_ATTACK_POWER
UNIT_RANGED_ATTACK_POWER
UNIT_RANGEDDAMAGE
UNIT_RANGEDDAMAGE
UNIT_MANA

UNIT_MANA

UNIT_STATS

UNIT_AURA
UNIT_COMBAT
UNIT_NAME_UPDATE
UNIT_PORTRAIT_UPDATE
UNIT_MODEL_CHANGED
UNIT_INVENTORY_CHANGED
UNIT_CLASSIFICATION_CHANGED
UNIT_COMBO_POINTS
ITEM_LOCK_CHANGED
PLAYER_XP_UPDATE
PLAYER_REGEN_DISABLED
PLAYER_REGEN_ENABLED
PLAYER_AURAS_CHANGED
PLAYER_ENTER_COMBAT
PLAYER_LEAVE_COMBAT
PLAYER_TARGET_CHANGED
PLAYER_FOCUS_CHANGED
PLAYER_CONTROL_LOST
PLAYER_CONTROL_GAINED
PLAYER_FARSIGHT_FOCUS_CHANGED
PLAYER_LEVEL_UP
PLAYER_MONEY
PLAYER_DAMAGE_DONE_MODS
PLAYER_TOTEM_UPDATE
ZONE_CHANGED
ZONE_CHANGED_INDOORS
ZONE_CHANGED_NEW_AREA
MINIMAP_UPDATE_ZOOM
MINIMAP_UPDATE_TRACKING
SCREENSHOT_SUCCEEDED
SCREENSHOT_FAILED
ACTIONBAR_SHOWGRID
ACTIONBAR_HIDEGRID
ACTIONBAR_PAGE_CHANGED
ACTIONBAR_SLOT_CHANGED
ACTIONBAR_UPDATE_STATE
ACTIONBAR_UPDATE_USABLE
ACTIONBAR_UPDATE_COOLDOWN
UPDATE_BONUS_ACTIONBAR
PARTY_MEMBERS_CHANGED
PARTY_LEADER_CHANGED
PARTY_MEMBER_ENABLE
PARTY_MEMBER_DISABLE
PARTY_LOOT_METHOD_CHANGED
SYSMSG
UI_ERROR_MESSAGE
UI_INFO_MESSAGE
UPDATE_CHAT_COLOR
CHAT_MSG_ADDON
CHAT_MSG_SYSTEM
CHAT_MSG_SAY
CHAT_MSG_PARTY
CHAT_MSG_RAID
CHAT_MSG_GUILD
CHAT_MSG_OFFICER
CHAT_MSG_YELL
CHAT_MSG_WHISPER
CHAT_MSG_WHISPER_INFORM
CHAT_MSG_EMOTE
CHAT_MSG_TEXT_EMOTE
CHAT_MSG_MONSTER_SAY
CHAT_MSG_MONSTER_PARTY
CHAT_MSG_MONSTER_YELL
CHAT_MSG_MONSTER_WHISPER
CHAT_MSG_MONSTER_EMOTE
CHAT_MSG_CHANNEL
CHAT_MSG_CHANNEL_JOIN
CHAT_MSG_CHANNEL_LEAVE
CHAT_MSG_CHANNEL_LIST
CHAT_MSG_CHANNEL_NOTICE
CHAT_MSG_CHANNEL_NOTICE_USER
CHAT_MSG_AFK
CHAT_MSG_DND
CHAT_MSG_IGNORED
CHAT_MSG_SKILL
CHAT_MSG_LOOT
CHAT_MSG_MONEY
CHAT_MSG_OPENING
CHAT_MSG_TRADESKILLS
CHAT_MSG_PET_INFO
CHAT_MSG_COMBAT_MISC_INFO
CHAT_MSG_COMBAT_XP_GAIN
CHAT_MSG_COMBAT_HONOR_GAIN
CHAT_MSG_COMBAT_FACTION_CHANGE
CHAT_MSG_BG_SYSTEM_NEUTRAL
CHAT_MSG_BG_SYSTEM_ALLIANCE
CHAT_MSG_BG_SYSTEM_HORDE
CHAT_MSG_RAID_LEADER
CHAT_MSG_RAID_WARNING
CHAT_MSG_RAID_BOSS_WHISPER
CHAT_MSG_RAID_BOSS_EMOTE
CHAT_MSG_FILTERED
CHAT_MSG_BATTLEGROUND
CHAT_MSG_BATTLEGROUND_LEADER
CHAT_MSG_RESTRICTED

CHAT_MSG_ACHIEVEMENT
CHAT_MSG_GUILD_ACHIEVEMENT
LANGUAGE_LIST_CHANGED
TIME_PLAYED_MSG
SPELLS_CHANGED
CURRENT_SPELL_CAST_CHANGED
SPELL_UPDATE_COOLDOWN
SPELL_UPDATE_USABLE
CHARACTER_POINTS_CHANGED
SKILL_LINES_CHANGED
ITEM_PUSH
LOOT_OPENED
LOOT_SLOT_CLEARED
LOOT_SLOT_CHANGED
LOOT_CLOSED
PLAYER_LOGIN
PLAYER_LOGOUT
PLAYER_ENTERING_WORLD
PLAYER_LEAVING_WORLD
PLAYER_ALIVE
PLAYER_DEAD
PLAYER_CAMPING
PLAYER_QUITING
LOGOUT_CANCEL
RESURRECT_REQUEST
PARTY_INVITE_REQUEST
PARTY_INVITE_CANCEL
GUILD_INVITE_REQUEST
GUILD_INVITE_CANCEL
GUILD_MOTD
TRADE_REQUEST
TRADE_REQUEST_CANCEL
LOOT_BIND_CONFIRM
EQUIP_BIND_CONFIRM
AUTOEQUIP_BIND_CONFIRM
USE_BIND_CONFIRM
DELETE_ITEM_CONFIRM
CURSOR_UPDATE
ITEM_TEXT_BEGIN
ITEM_TEXT_TRANSLATION
ITEM_TEXT_READY
ITEM_TEXT_CLOSED
GOSSIP_SHOW
GOSSIP_CONFIRM
GOSSIP_CONFIRM_CANCEL
GOSSIP_ENTER_CODE
GOSSIP_CLOSED
QUEST_GREETING
QUEST_DETAIL
QUEST_PROGRESS
QUEST_COMPLETE
QUEST_FINISHED
QUEST_ITEM_UPDATE
TAXIMAP_OPENED
TAXIMAP_CLOSED
QUEST_LOG_UPDATE
TRAINER_SHOW
TRAINER_UPDATE
TRAINER_DESCRIPTION_UPDATE
TRAINER_CLOSED
CVAR_UPDATE
TRADE_SKILL_SHOW
TRADE_SKILL_UPDATE
TRADE_SKILL_CLOSE
MERCHANT_SHOW
MERCHANT_UPDATE
MERCHANT_CLOSED
TRADE_SHOW
TRADE_CLOSED
TRADE_UPDATE
TRADE_ACCEPT_UPDATE
TRADE_TARGET_ITEM_CHANGED
TRADE_PLAYER_ITEM_CHANGED
TRADE_MONEY_CHANGED
PLAYER_TRADE_MONEY
BAG_OPEN
BAG_UPDATE
BAG_CLOSED
BAG_UPDATE_COOLDOWN
LOCALPLAYER_PET_RENAMED
UNIT_ATTACK
UNIT_DEFENSE
PET_ATTACK_START
PET_ATTACK_STOP
UPDATE_MOUSEOVER_UNIT
UNIT_SPELLCAST_SENT
UNIT_SPELLCAST_START
UNIT_SPELLCAST_STOP
UNIT_SPELLCAST_FAILED
UNIT_SPELLCAST_FAILED_QUIET
UNIT_SPELLCAST_INTERRUPTED
UNIT_SPELLCAST_DELAYED
UNIT_SPELLCAST_SUCCEEDED
UNIT_SPELLCAST_CHANNEL_START
UNIT_SPELLCAST_CHANNEL_UPDATE
UNIT_SPELLCAST_CHANNEL_STOP
UNIT_SPELLCAST_INTERRUPTIBLE
UNIT_SPELLCAST_NOT_INTERRUPTIBLE
PLAYER_GUILD_UPDATE
QUEST_ACCEPT_CONFIRM
PLAYERBANKSLOTS_CHANGED
BANKFRAME_OPENED
BANKFRAME_CLOSED
PLAYERBANKBAGSLOTS_CHANGED
FRIENDLIST_UPDATE
IGNORELIST_UPDATE
MUTELIST_UPDATE
PET_BAR_UPDATE
PET_BAR_UPDATE_COOLDOWN
PET_BAR_SHOWGRID
PET_BAR_HIDEGRID
PET_BAR_HIDE
PET_BAR_UPDATE_USABLE
MINIMAP_PING
MIRROR_TIMER_START
MIRROR_TIMER_PAUSE
MIRROR_TIMER_STOP
WORLD_MAP_UPDATE
WORLD_MAP_NAME_UPDATE
AUTOFOLLOW_BEGIN
AUTOFOLLOW_END

CINEMATIC_START
CINEMATIC_STOP
UPDATE_FACTION
CLOSE_WORLD_MAP
OPEN_TABARD_FRAME
CLOSE_TABARD_FRAME
TABARD_CANSAVE_CHANGED
GUILD_REGISTRAR_SHOW
GUILD_REGISTRAR_CLOSED
DUEL_REQUESTED
DUEL_OUTOFBOUNDS
DUEL_INBOUNDS
DUEL_FINISHED
TUTORIAL_TRIGGER
PET_DISMISS_START
UPDATE_BINDINGS
UPDATE_SHAPESHIFT_FORMS
UPDATE_SHAPESHIFT_FORM
UPDATE_SHAPESHIFT_USABLE
UPDATE_SHAPESHIFT_COOLDOWN
WHO_LIST_UPDATE
PETITION_SHOW
PETITION_CLOSED
EXECUTE_CHAT_LINE
UPDATE_MACROS
UPDATE_TICKET
UPDATE_CHAT_WINDOWS
CONFIRM_XP_LOSS
CORPSE_IN_RANGE
CORPSE_IN_INSTANCE
CORPSE_OUT_OF_RANGE
UPDATE_GM_STATUS
PLAYER_UNGHOST
BIND_ENCHANT
REPLACE_ENCHANT
TRADE_REPLACE_ENCHANT
TRADE_POTENTIAL_BIND_ENCHANT
PLAYER_UPDATE_RESTING
UPDATE_EXHAUSTION
PLAYER_FLAGS_CHANGED
GUILD_ROSTER_UPDATE
GM_PLAYER_INFO
MAIL_SHOW
MAIL_CLOSED
SEND_MAIL_MONEY_CHANGED
SEND_MAIL_COD_CHANGED
MAIL_SEND_INFO_UPDATE
MAIL_SEND_SUCCESS
MAIL_INBOX_UPDATE
MAIL_LOCK_SEND_ITEMS
MAIL_UNLOCK_SEND_ITEMS
BATTLEFIELDS_SHOW
BATTLEFIELDS_CLOSED
UPDATE_BATTLEFIELD_STATUS
UPDATE_BATTLEFIELD_SCORE
AUCTION_HOUSE_SHOW
AUCTION_HOUSE_CLOSED
NEW_AUCTION_UPDATE
AUCTION_ITEM_LIST_UPDATE
AUCTION_OWNED_LIST_UPDATE
AUCTION_BIDDER_LIST_UPDATE
PET_UI_UPDATE
PET_UI_CLOSE
ADDON_LOADED
VARIABLES_LOADED
MACRO_ACTION_FORBIDDEN
ADDON_ACTION_FORBIDDEN
MACRO_ACTION_BLOCKED
ADDON_ACTION_BLOCKED
START_AUTOREPEAT_SPELL
STOP_AUTOREPEAT_SPELL
PET_STABLE_SHOW
PET_STABLE_UPDATE
PET_STABLE_UPDATE_PAPERDOLL
PET_STABLE_CLOSED
RAID_ROSTER_UPDATE
UPDATE_PENDING_MAIL
UPDATE_INVENTORY_ALERTS
UPDATE_INVENTORY_DURABILITY
UPDATE_TRADESKILL_RECAST
OPEN_MASTER_LOOT_LIST
UPDATE_MASTER_LOOT_LIST
START_LOOT_ROLL
CANCEL_LOOT_ROLL
CONFIRM_LOOT_ROLL
CONFIRM_DISENCHANT_ROLL
INSTANCE_BOOT_START
INSTANCE_BOOT_STOP
LEARNED_SPELL_IN_TAB
DISPLAY_SIZE_CHANGED
CONFIRM_TALENT_WIPE
CONFIRM_BINDER
MAIL_FAILED
CLOSE_INBOX_ITEM
CONFIRM_SUMMON
CANCEL_SUMMON
BILLING_NAG_DIALOG
IGR_BILLING_NAG_DIALOG
PLAYER_SKINNED
TABARD_SAVE_PENDING
UNIT_QUEST_LOG_CHANGED
PLAYER_PVP_KILLS_CHANGED
PLAYER_PVP_RANK_CHANGED
INSPECT_HONOR_UPDATE
UPDATE_WORLD_STATES
AREA_SPIRIT_HEALER_IN_RANGE
AREA_SPIRIT_HEALER_OUT_OF_RANGE
PLAYTIME_CHANGED
UPDATE_LFG_TYPES
UPDATE_LFG_LIST
UPDATE_LFG_LIST_INCREMENTAL
START_MINIGAME
MINIGAME_UPDATE
READY_CHECK
READY_CHECK_CONFIRM
READY_CHECK_FINISHED
RAID_TARGET_UPDATE
GMSURVEY_DISPLAY
UPDATE_INSTANCE_INFO
SOCKET_INFO_UPDATE
SOCKET_INFO_CLOSE
PETITION_VENDOR_SHOW
PETITION_VENDOR_CLOSED
PETITION_VENDOR_UPDATE
COMBAT_TEXT_UPDATE
QUEST_WATCH_UPDATE
KNOWLEDGE_BASE_SETUP_LOAD_SUCCESS
KNOWLEDGE_BASE_SETUP_LOAD_FAILURE
KNOWLEDGE_BASE_QUERY_LOAD_SUCCESS
KNOWLEDGE_BASE_QUERY_LOAD_FAILURE
KNOWLEDGE_BASE_ARTICLE_LOAD_SUCCESS
KNOWLEDGE_BASE_ARTICLE_LOAD_FAILURE
KNOWLEDGE_BASE_SYSTEM_MOTD_UPDATED
KNOWLEDGE_BASE_SERVER_MESSAGE
ARENA_TEAM_UPDATE
ARENA_TEAM_ROSTER_UPDATE
ARENA_TEAM_INVITE_REQUEST
HONOR_CURRENCY_UPDATE
KNOWN_TITLES_UPDATE
NEW_TITLE_EARNED
OLD_TITLE_LOST
LFG_UPDATE
LFG_PROPOSAL_UPDATE
LFG_PROPOSAL_SHOW
LFG_PROPOSAL_FAILED
LFG_PROPOSAL_SUCCEEDED
LFG_ROLE_UPDATE
LFG_ROLE_CHECK_UPDATE
LFG_ROLE_CHECK_SHOW
LFG_ROLE_CHECK_HIDE
LFG_ROLE_CHECK_ROLE_CHOSEN
LFG_QUEUE_STATUS_UPDATE
LFG_BOOT_PROPOSAL_UPDATE
LFG_LOCK_INFO_RECEIVED
LFG_UPDATE_RANDOM_INFO
LFG_OFFER_CONTINUE
LFG_OPEN_FROM_GOSSIP
LFG_COMPLETION_REWARD
PARTY_LFG_RESTRICTED
PLAYER_ROLES_ASSIGNED
COMBAT_RATING_UPDATE
MODIFIER_STATE_CHANGED
UPDATE_STEALTH
ENABLE_TAXI_BENCHMARK
DISABLE_TAXI_BENCHMARK
VOICE_START
VOICE_STOP
VOICE_STATUS_UPDATE
VOICE_CHANNEL_STATUS_UPDATE
UPDATE_FLOATING_CHAT_WINDOWS
RAID_INSTANCE_WELCOME
MOVIE_RECORDING_PROGRESS
MOVIE_COMPRESSING_PROGRESS
MOVIE_UNCOMPRESSED_MOVIE
VOICE_PUSH_TO_TALK_START
VOICE_PUSH_TO_TALK_STOP
GUILDBANKFRAME_OPENED
GUILDBANKFRAME_CLOSED
GUILDBANKBAGSLOTS_CHANGED
GUILDBANK_ITEM_LOCK_CHANGED
GUILDBANK_UPDATE_TABS
GUILDBANK_UPDATE_MONEY
GUILDBANKLOG_UPDATE
GUILDBANK_UPDATE_WITHDRAWMONEY
GUILDBANK_UPDATE_TEXT
GUILDBANK_TEXT_CHANGED
CHANNEL_UI_UPDATE
CHANNEL_COUNT_UPDATE
CHANNEL_ROSTER_UPDATE
CHANNEL_VOICE_UPDATE
CHANNEL_INVITE_REQUEST
CHANNEL_PASSWORD_REQUEST
CHANNEL_FLAGS_UPDATED
VOICE_SESSIONS_UPDATE
VOICE_CHAT_ENABLED_UPDATE
VOICE_LEFT_SESSION
INSPECT_TALENT_READY
VOICE_SELF_MUTE
VOICE_PLATE_START
VOICE_PLATE_STOP
ARENA_SEASON_WORLD_STATE
GUILD_EVENT_LOG_UPDATE
GUILDTABARD_UPDATE
SOUND_DEVICE_UPDATE
COMMENTATOR_MAP_UPDATE
COMMENTATOR_ENTER_WORLD
COMBAT_LOG_EVENT
COMBAT_LOG_EVENT_UNFILTERED
COMMENTATOR_PLAYER_UPDATE
PLAYER_ENTERING_BATTLEGROUND
BARBER_SHOP_OPEN
BARBER_SHOP_CLOSE
BARBER_SHOP_SUCCESS
BARBER_SHOP_APPEARANCE_APPLIED
CALENDAR_UPDATE_INVITE_LIST
CALENDAR_UPDATE_EVENT_LIST
CALENDAR_NEW_EVENT
CALENDAR_OPEN_EVENT
CALENDAR_CLOSE_EVENT
CALENDAR_UPDATE_EVENT
CALENDAR_UPDATE_PENDING_INVITES
CALENDAR_EVENT_ALARM
CALENDAR_UPDATE_ERROR
CALENDAR_ACTION_PENDING
VEHICLE_ANGLE_SHOW
VEHICLE_ANGLE_UPDATE
VEHICLE_POWER_SHOW
UNIT_ENTERING_VEHICLE
UNIT_ENTERED_VEHICLE
UNIT_EXITING_VEHICLE
UNIT_EXITED_VEHICLE
VEHICLE_PASSENGERS_CHANGED
PLAYER_GAINS_VEHICLE_DATA
PLAYER_LOSES_VEHICLE_DATA
PET_FORCE_NAME_DECLENSION
LEVEL_GRANT_PROPOSED
SYNCHRONIZE_SETTINGS
PLAY_MOVIE
RUNE_POWER_UPDATE
RUNE_TYPE_UPDATE
ACHIEVEMENT_EARNED
CRITERIA_UPDATE
RECEIVED_ACHIEVEMENT_LIST
PET_RENAMEABLE
KNOWN_CURRENCY_TYPES_UPDATE
CURRENCY_DISPLAY_UPDATE
COMPANION_LEARNED
COMPANION_UNLEARNED
COMPANION_UPDATE
UNIT_THREAT_LIST_UPDATE
UNIT_THREAT_SITUATION_UPDATE
GLYPH_ADDED
GLYPH_REMOVED
GLYPH_UPDATED
GLYPH_ENABLED
GLYPH_DISABLED
USE_GLYPH
TRACKED_ACHIEVEMENT_UPDATE
ARENA_OPPONENT_UPDATE
INSPECT_ACHIEVEMENT_READY
RAISED_AS_GHOUL
PARTY_CONVERTED_TO_RAID
PVPQUEUE_ANYWHERE_SHOW
PVPQUEUE_ANYWHERE_UPDATE_AVAILABLE
QUEST_ACCEPTED
PLAYER_TALENT_UPDATE
ACTIVE_TALENT_GROUP_CHANGED
PET_TALENT_UPDATE
PREVIEW_TALENT_POINTS_CHANGED
PREVIEW_PET_TALENT_POINTS_CHANGED
WEAR_EQUIPMENT_SET
EQUIPMENT_SETS_CHANGED
INSTANCE_LOCK_START
INSTANCE_LOCK_STOP
PLAYER_EQUIPMENT_CHANGED
ITEM_LOCKED
ITEM_UNLOCKED
TRADE_SKILL_FILTER_UPDATE
EQUIPMENT_SWAP_PENDING
EQUIPMENT_SWAP_FINISHED
NPC_PVPQUEUE_ANYWHERE
UPDATE_MULTI_CAST_ACTIONBAR
ENABLE_XP_GAIN
DISABLE_XP_GAIN
BATTLEFIELD_MGR_ENTRY_INVITE
BATTLEFIELD_MGR_ENTERED
BATTLEFIELD_MGR_QUEUE_REQUEST_RESPONSE
BATTLEFIELD_MGR_EJECT_PENDING
BATTLEFIELD_MGR_EJECTED
BATTLEFIELD_MGR_QUEUE_INVITE
BATTLEFIELD_MGR_STATE_CHANGE
WORLD_STATE_UI_TIMER_UPDATE
END_REFUND
END_BOUND_TRADEABLE
UPDATE_CHAT_COLOR_NAME_BY_CLASS
GMRESPONSE_RECEIVED
VEHICLE_UPDATE
WOW_MOUSE_NOT_FOUND

MAIL_SUCCESS
TALENTS_INVOLUNTARILY_RESET
INSTANCE_ENCOUNTER_ENGAGE_UNIT
QUEST_QUERY_COMPLETE
QUEST_POI_UPDATE
PLAYER_DIFFICULTY_CHANGED
CHAT_MSG_PARTY_LEADER
VOTE_KICK_REASON_NEEDED
ENABLE_LOW_LEVEL_RAID
DISABLE_LOW_LEVEL_RAID
CHAT_MSG_TARGETICONS
AUCTION_HOUSE_DISABLED
AUCTION_MULTISELL_START
AUCTION_MULTISELL_UPDATE
AUCTION_MULTISELL_FAILURE
PET_SPELL_POWER_UPDATE
BN_CONNECTED
BN_DISCONNECTED
BN_SELF_ONLINE
BN_SELF_OFFLINE
BN_FRIEND_LIST_SIZE_CHANGED
BN_FRIEND_INVITE_LIST_INITIALIZED
BN_FRIEND_INVITE_SEND_RESULT
BN_FRIEND_INVITE_ADDED
BN_FRIEND_INVITE_REMOVED
BN_FRIEND_INFO_CHANGED
BN_CUSTOM_MESSAGE_CHANGED
BN_CUSTOM_MESSAGE_LOADED
CHAT_MSG_BN_WHISPER
CHAT_MSG_BN_WHISPER_INFORM
BN_CHAT_WHISPER_UNDELIVERABLE
BN_CHAT_CHANNEL_JOINED
BN_CHAT_CHANNEL_LEFT
BN_CHAT_CHANNEL_CLOSED
CHAT_MSG_BN_CONVERSATION
CHAT_MSG_BN_CONVERSATION_NOTICE
CHAT_MSG_BN_CONVERSATION_LIST
BN_CHAT_CHANNEL_MESSAGE_UNDELIVERABLE
BN_CHAT_CHANNEL_MESSAGE_BLOCKED
BN_CHAT_CHANNEL_MEMBER_JOINED
BN_CHAT_CHANNEL_MEMBER_LEFT
BN_CHAT_CHANNEL_MEMBER_UPDATED
BN_CHAT_CHANNEL_CREATE_SUCCEEDED
BN_CHAT_CHANNEL_CREATE_FAILED
BN_CHAT_CHANNEL_INVITE_SUCCEEDED
BN_CHAT_CHANNEL_INVITE_FAILED
BN_BLOCK_LIST_UPDATED
BN_SYSTEM_MESSAGE
BN_REQUEST_FOF_SUCCEEDED
BN_REQUEST_FOF_FAILED
BN_NEW_PRESENCE
BN_TOON_NAME_UPDATED
BN_FRIEND_ACCOUNT_ONLINE
BN_FRIEND_ACCOUNT_OFFLINE
BN_FRIEND_TOON_ONLINE
BN_FRIEND_TOON_OFFLINE
BN_MATURE_LANGUAGE_FILTER
COMMENTATOR_SKIRMISH_QUEUE_REQUEST
COMMENTATOR_SKIRMISH_MODE_REQUEST
CHAT_MSG_BN_INLINE_TOAST_ALERT
CHAT_MSG_BN_INLINE_TOAST_BROADCAST
CHAT_MSG_BN_INLINE_TOAST_BROADCAST_INFORM
CHAT_MSG_BN_INLINE_TOAST_CONVERSATION)";

bool StartsWith(std::string_view value, std::string_view prefix) {
  return value.substr(0, prefix.size()) == prefix;
}

bool Contains(std::string_view value, std::string_view needle) {
  return value.find(needle) != std::string_view::npos;
}

ScriptEventDomain InferDomain(std::string_view name) {
  if (StartsWith(name, "UNIT_")) return ScriptEventDomain::Unit;
  if (StartsWith(name, "PLAYER_")) return ScriptEventDomain::Player;
  if (StartsWith(name, "CHAT_MSG_")) return ScriptEventDomain::Chat;
  if (StartsWith(name, "BN_") || Contains(name, "_BN_")) {
    return ScriptEventDomain::Battlenet;
  }
  if (StartsWith(name, "ADDON_") || name == "VARIABLES_LOADED") {
    return ScriptEventDomain::AddOn;
  }
  if (StartsWith(name, "COMBAT_")) return ScriptEventDomain::Combat;
  if (StartsWith(name, "CINEMATIC_") || StartsWith(name, "MOVIE_") ||
      name == "PLAY_MOVIE") {
    return ScriptEventDomain::Cinematic;
  }
  if (StartsWith(name, "VEHICLE_")) return ScriptEventDomain::Vehicle;
  if (StartsWith(name, "PARTY_") || StartsWith(name, "RAID_") ||
      StartsWith(name, "GROUP_") || StartsWith(name, "READY_CHECK")) {
    return ScriptEventDomain::Group;
  }
  if (StartsWith(name, "LOOT_") || Contains(name, "_LOOT_")) {
    return ScriptEventDomain::Loot;
  }
  if (StartsWith(name, "TRADE_") || StartsWith(name, "MERCHANT_") ||
      StartsWith(name, "AUCTION_")) {
    return ScriptEventDomain::Trade;
  }
  if (StartsWith(name, "QUEST_") || StartsWith(name, "GOSSIP_")) {
    return ScriptEventDomain::Quest;
  }
  return ScriptEventDomain::System;
}

ScriptEventPayloadKind InferPayload(std::string_view name) {

  if (StartsWith(name, "UNIT_SPELLCAST_")) {
    return ScriptEventPayloadKind::Spellcast;
  }
  if (name == "CHAT_MSG_ADDON") return ScriptEventPayloadKind::AddOnMessage;
  if (name == "ADDON_LOADED") return ScriptEventPayloadKind::AddOnName;
  if (name == "COMBAT_LOG_EVENT" ||
      name == "COMBAT_LOG_EVENT_UNFILTERED") {
    return ScriptEventPayloadKind::CombatLog;
  }
  if (StartsWith(name, "UNIT_")) return ScriptEventPayloadKind::UnitToken;
  if (StartsWith(name, "CHAT_MSG_")) return ScriptEventPayloadKind::ChatMessage;
  if (name == "SYSMSG" || name == "UI_ERROR_MESSAGE" ||
      name == "UI_INFO_MESSAGE" || name == "BN_SYSTEM_MESSAGE") {
    return ScriptEventPayloadKind::Message;
  }
  if (name == "CVAR_UPDATE") return ScriptEventPayloadKind::CVarUpdate;
  if (StartsWith(name, "BAG_")) return ScriptEventPayloadKind::BagId;
  if (StartsWith(name, "LOOT_SLOT_")) return ScriptEventPayloadKind::LootSlot;
  if (Contains(name, "MONEY")) return ScriptEventPayloadKind::Money;
  return ScriptEventPayloadKind::None;
}

std::uint8_t MinArgsForPayload(ScriptEventPayloadKind payload) {
  switch (payload) {
    case ScriptEventPayloadKind::UnitToken:
    case ScriptEventPayloadKind::AddOnName:
    case ScriptEventPayloadKind::Message:
    case ScriptEventPayloadKind::CVarUpdate:
    case ScriptEventPayloadKind::BagId:
    case ScriptEventPayloadKind::LootSlot:
    case ScriptEventPayloadKind::Money:
      return 1;
    case ScriptEventPayloadKind::ChatMessage:
      return 2;
    case ScriptEventPayloadKind::AddOnMessage:
      return 4;
    case ScriptEventPayloadKind::CombatLog:

      return 8;
    case ScriptEventPayloadKind::Spellcast:
      return 1;
    case ScriptEventPayloadKind::None:
      return 0;
  }
  return 0;
}

}

std::size_t ScriptEventCatalog::AsciiNoCaseHash::operator()(
    const std::string_view value) const noexcept {

  std::size_t hash = sizeof(std::size_t) == 8
                         ? static_cast<std::size_t>(14695981039346656037ull)
                         : static_cast<std::size_t>(2166136261u);
  const std::size_t prime = sizeof(std::size_t) == 8
                                ? static_cast<std::size_t>(1099511628211ull)
                                : static_cast<std::size_t>(16777619u);
  for (const unsigned char character : value) {
    const unsigned char folded =
        character >= 'a' && character <= 'z'
            ? static_cast<unsigned char>(character - ('a' - 'A'))
            : character;
    hash ^= folded;
    hash *= prime;
  }
  return hash;
}

bool ScriptEventCatalog::AsciiNoCaseEqual::operator()(
    const std::string_view lhs, const std::string_view rhs) const noexcept {
  if (lhs.size() != rhs.size()) {
    return false;
  }
  for (std::size_t index = 0; index < lhs.size(); ++index) {
    const auto fold = [](const unsigned char character) {
      return character >= 'a' && character <= 'z'
                 ? static_cast<unsigned char>(character - ('a' - 'A'))
                 : character;
    };
    if (fold(static_cast<unsigned char>(lhs[index])) !=
        fold(static_cast<unsigned char>(rhs[index]))) {
      return false;
    }
  }
  return true;
}

ScriptEventCatalog::ScriptEventCatalog() {
  constexpr std::size_t kMissingDescriptor =
      std::numeric_limits<std::size_t>::max();
  events_.reserve(647);
  lookup_.reserve(647);
  id_lookup_.reserve(722);
  std::size_t line_start = 0;
  std::uint16_t id = 0;
  while (line_start <= kRetailWorldEvents.size()) {
    const std::size_t line_end = kRetailWorldEvents.find('\n', line_start);
    const std::size_t token_end =
        line_end == std::string_view::npos ? kRetailWorldEvents.size()
                                           : line_end;
    const std::string_view name =
        kRetailWorldEvents.substr(line_start, token_end - line_start);
    if (!name.empty()) {
      const auto payload = InferPayload(name);
      const auto domain = InferDomain(name);
      const auto event_index = events_.size();
      events_.push_back(ScriptEventDescriptor{
          id, name, domain, payload, MinArgsForPayload(payload),
          domain == ScriptEventDomain::Battlenet, true});
      lookup_.emplace(name, event_index);
      if (id_lookup_.size() <= id) {
        id_lookup_.resize(static_cast<std::size_t>(id) + 1u,
                          kMissingDescriptor);
      }
      id_lookup_[id] = event_index;
    } else if (id_lookup_.size() <= id) {
      id_lookup_.resize(static_cast<std::size_t>(id) + 1u,
                        kMissingDescriptor);
    }
    if (line_end == std::string_view::npos) break;
    line_start = line_end + 1;
    ++id;
  }
}

const ScriptEventCatalog& ScriptEventCatalog::Instance() {
  static const ScriptEventCatalog catalog;
  return catalog;
}

const ScriptEventDescriptor* ScriptEventCatalog::Find(
    std::string_view name) const {
  const auto it = lookup_.find(name);
  return it != lookup_.end() ? &events_[it->second] : nullptr;
}

const ScriptEventDescriptor* ScriptEventCatalog::FindById(
    std::uint16_t id) const {
  static constexpr ScriptEventDescriptor kRetailEmptyEvent{
      237, "", ScriptEventDomain::System, ScriptEventPayloadKind::None, 0,
      false, false};
  if (id == kRetailEmptyEvent.id) {
    return &kRetailEmptyEvent;
  }
  constexpr std::size_t kMissingDescriptor =
      std::numeric_limits<std::size_t>::max();
  if (id >= id_lookup_.size() || id_lookup_[id] == kMissingDescriptor) {
    return nullptr;
  }
  return &events_[id_lookup_[id]];
}

std::optional<std::uint16_t> ScriptEventCatalog::Intern(
    std::string_view name) const {
  if (const auto* descriptor = Find(name); descriptor != nullptr) {
    return descriptor->id;
  }
  return std::nullopt;
}

bool ScriptEventCatalog::IsKnown(std::string_view name) const {
  return Find(name) != nullptr;
}

bool ScriptEventCatalog::IsPayloadShapeValid(
    std::string_view name, std::size_t payload_arg_count) const {
  const auto* descriptor = Find(name);
  return descriptor != nullptr &&
         payload_arg_count >= descriptor->min_payload_args;
}

}
