
if(NOT TARGET openwow-client)
  return()
endif()

set(CPACK_PACKAGE_NAME "openwow-client")
set(CPACK_PACKAGE_VENDOR "OpenWoW contributors")
set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}")
set(CPACK_PACKAGE_VERSION_MAJOR "${PROJECT_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${PROJECT_VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${PROJECT_VERSION_PATCH}")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY
  "OpenWoW: from-scratch reimplementation of the World of Warcraft 3.3.5a client")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://github.com/OpenWoW/OpenWoW")
set(CPACK_RESOURCE_FILE_README "${PROJECT_SOURCE_DIR}/../README.md")
if(NOT EXISTS "${CPACK_RESOURCE_FILE_README}")
  unset(CPACK_RESOURCE_FILE_README)
endif()

set(CPACK_COMPONENTS_ALL client)
set(CPACK_ARCHIVE_COMPONENT_INSTALL ON)
set(CPACK_COMPONENTS_GROUPING ALL_COMPONENTS_IN_ONE)
set(CPACK_MONOLITHIC_INSTALL OFF)

if(APPLE)
  set(OPENWOW_PACKAGE_OS "macos")
  set(CPACK_GENERATOR "ZIP")
elseif(WIN32)
  set(OPENWOW_PACKAGE_OS "windows")
  set(CPACK_GENERATOR "ZIP")
else()
  string(TOLOWER "${CMAKE_SYSTEM_NAME}" OPENWOW_PACKAGE_OS)
  set(CPACK_GENERATOR "TGZ")
endif()

if(CMAKE_OSX_ARCHITECTURES)
  string(REPLACE ";" "-" OPENWOW_PACKAGE_ARCH "${CMAKE_OSX_ARCHITECTURES}")
  list(LENGTH CMAKE_OSX_ARCHITECTURES OPENWOW_OSX_ARCH_COUNT)
  if(OPENWOW_OSX_ARCH_COUNT GREATER 1)
    set(OPENWOW_PACKAGE_ARCH "universal")
  endif()
elseif(CMAKE_SYSTEM_PROCESSOR)
  string(TOLOWER "${CMAKE_SYSTEM_PROCESSOR}" OPENWOW_PACKAGE_ARCH)

  if(OPENWOW_PACKAGE_ARCH STREQUAL "amd64")
    set(OPENWOW_PACKAGE_ARCH "x86_64")
  elseif(OPENWOW_PACKAGE_ARCH STREQUAL "aarch64" AND (APPLE OR WIN32))
    set(OPENWOW_PACKAGE_ARCH "arm64")
  elseif(OPENWOW_PACKAGE_ARCH STREQUAL "arm64" AND NOT (APPLE OR WIN32))
    set(OPENWOW_PACKAGE_ARCH "aarch64")
  endif()
else()
  set(OPENWOW_PACKAGE_ARCH "unknown")
endif()

set(CPACK_PACKAGE_FILE_NAME
  "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}-${OPENWOW_PACKAGE_OS}-${OPENWOW_PACKAGE_ARCH}")
set(CPACK_INCLUDE_TOPLEVEL_DIRECTORY OFF)
set(CPACK_ARCHIVE_CLIENT_FILE_NAME "${CPACK_PACKAGE_FILE_NAME}")
set(CPACK_STRIP_FILES OFF)
set(CPACK_SOURCE_GENERATOR "")

include(CPack)
cpack_add_component(client
  DISPLAY_NAME "OpenWoW client"
  DESCRIPTION "The drop-in game client executable"
  REQUIRED
)
