#include "openwow/ui/game/api/framexml_core_native_bindings.h"

#include "openwow/ui/game/api/held_cursor_lua_api.h"
#include "openwow/game/actions/macros/adapters/lua/macro_lua_api.h"
#include "openwow/ui/glue/glue_lua_shared_handlers.h"
#include "openwow/ui/game/api/game_lua_api_addon.h"
#include "openwow/ui/game/api/game_lua_api_binding.h"
#include "openwow/ui/game/api/game_lua_api_chat.h"
#include "openwow/ui/game/api/game_lua_api_cvar.h"
#include "openwow/ui/game/api/game_lua_api_misc.h"
#include "openwow/ui/game/api/game_lua_api_misc_ui.h"
#include "openwow/ui/game/api/game_lua_api_system.h"
#include "openwow/ui/game/api/game_lua_api_ui_util.h"
#include "openwow/ui/game/framescript/core/frame_method_registry.h"
#include "openwow/ui/lua_binding_registry.h"
#include "openwow/ui/runtime/lua/lua_composition.h"

namespace openwow::ui::game::detail {

namespace macro_lua =
    ::openwow::game::actions::macros::adapters::lua;

namespace {

constexpr openwow::ui::LuaGlobalBinding kWorldTimeSystemBindings[] = {
    {"GetTime", LuaGameGetTime},
    {"GetGameTime", LuaGetGameTime},
};

constexpr openwow::ui::LuaGlobalBinding kSystemLuaBindings[] = {
    {"ReadFile", openwow::ui::glue::detail::LuaScriptFileAccessDenied},
    {"DeleteFile", openwow::ui::glue::detail::LuaScriptFileAccessDenied},
    {"AppendToFile", openwow::ui::glue::detail::LuaScriptFileAccessDenied},
    {"GetFramerate", LuaGetFramerate},
    {"GetNetStats", LuaGetNetStats},
    {"GetDebugStats", LuaGetDebugStats},
    {"GetExtendedItemInfo", LuaRetailReleaseDebugCommand},
    {"ToggleTris", LuaRetailReleaseDebugCommand},
    {"TogglePortals", LuaRetailReleaseDebugCommand},
    {"ToggleCollision", LuaRetailReleaseDebugCommand},
    {"ToggleCollisionDisplay", LuaRetailReleaseDebugCommand},
    {"TogglePerformancePause", LuaRetailReleaseDebugCommand},
    {"TogglePerformanceDisplay", LuaRetailReleaseDebugCommand},
    {"TogglePerformanceValues", LuaRetailReleaseDebugCommand},
    {"ResetPerformanceValues", LuaRetailReleaseDebugCommand},
    {"TogglePlayerBounds", LuaRetailReleaseDebugCommand},
    {"GetCursorPosition", LuaGameGetCursorPosition},
    {"SetCursor", LuaSetCursor},
    {"ResetCursor", LuaResetCursor},
    {"AutoEquipCursorItem", LuaAutoEquipCursorItem},
    {"DeleteCursorItem", LuaDeleteCursorItem},
    {"GetCursorInfo", LuaGetCursorInfo},
    {"ClearCursor", LuaClearCursor},
    {"PickupItem", LuaPickupItem},
    {"PickupInventoryItem", LuaPickupInventoryItem},
    {"PickupPetAction", LuaPickupPetAction},
    {"PickupMacro", LuaPickupMacro},
    {"PickupBagFromSlot", LuaPickupBagFromSlot},
    {"CursorCanGoInSlot", LuaCursorCanGoInSlot},
    {"PutItemInBag", LuaPutItemInBag},
    {"PutItemInBackpack", LuaPutItemInBackpack},
    {"DropItemOnUnit", LuaDropItemOnUnit},
    {"EquipCursorItem", LuaEquipCursorItem},
    {"InRepairMode", LuaInRepairMode},
    {"ShowRepairCursor", LuaShowRepairCursor},
    {"HideRepairCursor", LuaHideRepairCursor},
    {"Logout", LuaLogout},
    {"ForceLogout", LuaForceLogout},
    {"CancelLogout", LuaCancelLogout},
    {"OpeningCinematic", LuaOpeningCinematic},
    {"GetBillingTimeRested", LuaGetBillingTimeRested},
    {"GetRestState", LuaGetRestState},
    {"GetXPExhaustion", LuaGetXPExhaustion},
    {"GetTimeToWellRested", LuaGetTimeToWellRestedRetail},
    {"IsResting", LuaIsResting},
    {"IsMounted", LuaIsMounted},
    {"Dismount", LuaDismount},
    {"IsSwimming", LuaIsSwimming},
    {"IsFalling", LuaIsFalling},
    {"IsFlying", LuaIsFlying},
    {"IsStealthed", LuaIsStealthed},
    {"GetWeaponEnchantInfo", LuaGetWeaponEnchantInfo},
    {"GetBuildInfo", LuaGetBuildInfo},
    {"IsWindowsClient", LuaIsWindowsClient},
    {"IsMacClient", LuaIsMacClient},
    {"IsLinuxClient", LuaIsLinuxClient},
    {"GetExpansionLevel", LuaGetExpansionLevel},
    {"IsDebugBuild", LuaApi_IsDebugBuild},
    {"SetConsoleKey", LuaApi_SetConsoleKey},
    {"SetEuropeanNumbers", LuaApi_SetEuropeanNumbers},
    {"GetRealmName", LuaGetRealmName},
    {"GetAddOnMemoryUsage", kGetAddOnMemoryUsage.handler},
    {"GetAddOnCPUUsage", kGetAddOnCPUUsage.handler},
    {"GetScriptCPUUsage", LuaGetScriptCPUUsage},
    {"ResetCPUUsage", LuaResetCPUUsage},
    {"IsShiftKeyDown", LuaIsShiftKeyDown},
    {"IsControlKeyDown", LuaIsControlKeyDown},
    {"IsAltKeyDown", LuaIsAltKeyDown},
    {"IsModifierKeyDown", LuaIsModifierKeyDown},
    {"IsLeftShiftKeyDown", LuaIsLeftShiftKeyDown},
    {"IsRightShiftKeyDown", LuaIsRightShiftKeyDown},
    {"IsLeftControlKeyDown", LuaIsLeftControlKeyDown},
    {"IsRightControlKeyDown", LuaIsRightControlKeyDown},
    {"IsLeftAltKeyDown", LuaIsLeftAltKeyDown},
    {"IsRightAltKeyDown", LuaIsRightAltKeyDown},
    {"IsModifiedClick", LuaIsModifiedClick},
    {"SetModifiedClick", LuaSetModifiedClick},
    {"GetModifiedClick", LuaGetModifiedClick},
    {"RunScript", LuaRunScript},
    {"IsLoggedIn", LuaIsLoggedIn},
    {"GameMovieFinished", LuaGameMovieFinished},
    {"StopCinematic", LuaStopCinematic},
    {"Screenshot", LuaScreenshot},
    {"MovieRecording_Toggle", LuaMovieRecordingToggle},
    {"MovieRecording_Cancel", LuaMovieRecordingCancel},
    {"MovieRecording_IsRecording", LuaMovieRecordingIsRecording},
    {"MovieRecording_IsCompressing", LuaMovieRecordingIsCompressing},
    {"MovieRecording_GetProgress", LuaMovieRecordingGetProgress},
    {"MovieRecording_GetViewportWidth", LuaMovieRecordingGetViewportWidth},
    {"MovieRecording_GetAspectRatio", LuaMovieRecordingGetAspectRatio},
    {"MovieRecording_IsSupported", LuaMovieRecordingIsSupported},
    {"MovieRecording_IsCodecSupported", LuaMovieRecordingIsCodecSupported},
    {"MovieRecording_IsCursorRecordingSupported", LuaMovieRecordingIsCursorRecordingSupported},
    {"MovieRecording_MaxLength", LuaMovieRecordingMaxLength},
    {"MovieRecording_DataRate", LuaMovieRecordingDataRate},
    {"MovieRecording_GetTime", LuaMovieRecordingGetTime},
    {"MovieRecording_GetMovieFullPath", LuaMovieRecordingGetMovieFullPath},
    {"MovieRecording_SearchUncompressedMovie", LuaMovieRecordingSearchUncompressedMovie},
    {"MovieRecording_QueueMovieToCompress", LuaMovieRecordingQueueMovieToCompress},
    {"MovieRecording_DeleteMovie", LuaMovieRecordingDeleteMovie},
    {"MovieRecording_ToggleGUI", LuaMovieRecordingToggleGUI},
    {"GetNumBindings", kGetNumBindings.handler},
    {"GetNumModifiedClickActions", kGetNumModifiedClickActions.handler},
    {"GetBinding", kGetBinding.handler},
    {"GetBindingKey", kGetBindingKey.handler},
    {"GetBindingAction", kGetBindingAction.handler},
    {"SetBinding", kSetBinding.handler},
    {"SetBindingSpell", kSetBindingSpell.handler},
    {"SetBindingItem", kSetBindingItem.handler},
    {"SetBindingMacro", kSetBindingMacro.handler},
    {"SetBindingClick", kSetBindingClick.handler},
    {"SetOverrideBinding", kSetOverrideBinding.handler},
    {"ClearOverrideBindings", kClearOverrideBindings.handler},
    {"SaveBindings", kSaveBindings.handler},
    {"LoadBindings", kLoadBindings.handler},
    {"GetCurrentBindingSet", kGetCurrentBindingSet.handler},
    {"RunBinding", kRunBinding.handler},
    {"GetBindingByKey", kGetBindingByKey.handler},
    {"GetCVar", kGetCVar.handler},
    {"GetFarclip", kGetFarclip.handler},
    {"SetFarclip", kSetFarclip.handler},
    {"GetTexLodBias", kGetTexLodBias.handler},
    {"SetTexLodBias", kSetTexLodBias.handler},
    {"SetCVar", kSetCVar.handler},
    {"GetBaseMip", kGetBaseMip.handler},
    {"GetCVarBool", kGetCVarBool.handler},
    {"GetCVarDefault", kGetCVarDefault.handler},
    {"GetCVarInfo", kGetCVarInfo.handler},
    {"GetCVarMax", kGetCVarMax.handler},
    {"GetCVarMin", kGetCVarMin.handler},
    {"GetCVarAbsoluteMax", kGetCVarAbsoluteMax.handler},
    {"GetCVarAbsoluteMin", kGetCVarAbsoluteMin.handler},
    {"RegisterCVar", kRegisterCVar.handler},
    {"RegisterStaticConstants", LuaApi_RegisterStaticConstants},
    {"SetBaseMip", kSetBaseMip.handler},
    {"SetWaterDetail", kSetWaterDetail.handler},
    {"GetWaterDetail", LuaGetWaterDetailRetail},
    {"GetAddOnInfo", kGetAddOnInfo.handler},
    {"EnableAddOn", kEnableAddOn.handler},
    {"DisableAddOn", kDisableAddOn.handler},
    {"LoadAddOn", kLoadAddOn.handler},
    {"IsAddOnLoaded", kIsAddOnLoaded.handler},
    {"IsAddOnLoadOnDemand", kIsAddOnLoadOnDemand.handler},
    {"EnableAllAddOns", kEnableAllAddOns.handler},
    {"DisableAllAddOns", kDisableAllAddOns.handler},
    {"GetAddOnDependencies", kGetAddOnDependencies.handler},
    {"ResetDisabledAddOns", kResetDisabledAddOns.handler},
    {"GetAddOnMetadata", kGetAddOnMetadata.handler},
    {"SetOverrideBindingSpell", kSetOverrideBindingSpell.handler},
    {"SetOverrideBindingClick", kSetOverrideBindingClick.handler},
    {"SetOverrideBindingItem", kSetOverrideBindingItem.handler},
    {"SetOverrideBindingMacro", kSetOverrideBindingMacro.handler},
    {"GetNumMacros", macro_lua::LuaGetNumMacros},
    {"GetMacroInfo", macro_lua::LuaGetMacroInfo},
    {"GetMacroBody", macro_lua::LuaGetMacroBody},
    {"CreateMacro", macro_lua::LuaCreateMacro},
    {"EditMacro", macro_lua::LuaEditMacro},
    {"DeleteMacro", macro_lua::LuaDeleteMacro},
    {"GetMacroIndexByName", macro_lua::LuaGetMacroIndexByName},
    {"GetRunningMacro", macro_lua::LuaGetRunningMacro},
    {"GetRunningMacroButton", macro_lua::LuaGetRunningMacroButton},
    {"SetMacroItem", macro_lua::LuaSetMacroItem},
    {"GetMacroItem", macro_lua::LuaGetMacroItem},
    {"SetMacroSpell", macro_lua::LuaSetMacroSpell},
    {"GetNumMacroIcons", macro_lua::LuaGetNumMacroIcons},
    {"GetNumMacroItemIcons", macro_lua::LuaGetNumMacroItemIcons},
    {"RunMacro", macro_lua::LuaRunMacro},
    {"RunMacroText", macro_lua::LuaRunMacroText},
    {"SecureCmdOptionParse", macro_lua::LuaSecureCmdOptionParse},
    {"SetPortraitTexture", LuaSetPortraitTexture},
    {"SetPortraitToTexture", LuaSetPortraitToTexture},
    {"Quit", LuaQuit},
    {"ForceQuit", LuaForceQuit},
    {"AcceptResurrect", LuaAcceptResurrect},
    {"DeclineResurrect", LuaDeclineResurrect},
    {"RepopMe", LuaRepopMe},
    {"RetrieveCorpse", LuaRetrieveCorpse},
    {"GetCorpseRecoveryDelay", LuaGetCorpseRecoveryDelay},
    {"GetReleaseTimeRemaining", LuaGetReleaseTimeRemaining},
    {"ResurrectGetOfferer", LuaResurrectGetOfferer},
    {"ResurrectHasSickness", LuaResurrectHasSickness},
    {"ResurrectHasTimer", LuaResurrectHasTimer},
    {"GetLocale", LuaGetLocale},
    {"IsXPUserDisabled", LuaIsXPUserDisabled},
    {"GetCursorMoney", LuaGetCursorMoney},
    {"GetMouseFocus", LuaGetMouseFocus},
    {"GetMouseButtonClicked", LuaGetMouseButtonClicked},
    {"IsMouseButtonDown", LuaIsMouseButtonDown},
    {"GetMovieResolution", openwow::ui::glue::detail::LuaGetMovieResolution},
    {"RestoreVideoEffectsDefaults",
     openwow::ui::glue::detail::LuaRestoreVideoEffectsDefaults},
    {"RestoreVideoResolutionDefaults",
     openwow::ui::glue::detail::LuaRestoreVideoResolutionDefaults},
    {"RestoreVideoStereoDefaults",
     openwow::ui::glue::detail::LuaRestoreVideoStereoDefaults},
    {"RandomRoll", LuaRandomRoll},
    {"RestartGx", LuaRestartGx},
    {"ConsoleExec", openwow::ui::glue::detail::LuaConsoleExec},
    {"GetExistingLocales", LuaGetExistingLocales},
    {"AcceptAreaSpiritHeal", LuaAcceptAreaSpiritHeal},
    {"CancelAreaSpiritHeal", LuaCancelAreaSpiritHeal},
    {"CursorHasItem", LuaCursorHasItem},
    {"CursorHasMacro", LuaCursorHasMacro},
    {"CursorHasMoney", LuaCursorHasMoney},
    {"CursorHasSpell", LuaCursorHasSpell},
    {"DropCursorMoney", LuaDropCursorMoney},
    {"FillLocalizedClassList", LuaFillLocalizedClassList},
    {"FrameXML_Debug", LuaFrameXML_Debug},
    {"GetAccountExpansionLevel", LuaGetAccountExpansionLevel},
    {"GetAreaSpiritHealerTime", LuaGetAreaSpiritHealerTime},
    {"GetClickFrame", LuaGetClickFrame},
    {"GetMacroIconInfo", macro_lua::LuaGetMacroIconInfo},
    {"GetMacroSpell", macro_lua::LuaGetMacroSpell},
    {"GetMinigameState", LuaGetMinigameState},
    {"GetMinigameType", LuaGetMinigameType},
    {"GetScreenHeight", LuaGetScreenHeight},
    {"GetScreenWidth", LuaGetScreenWidth},
    {"InCinematic", LuaInCinematic},
    {"IsOutOfBounds", LuaIsOutOfBounds},
    {"PickupPlayerMoney", LuaPickupPlayerMoney},
    {"RegisterForSave", LuaRegisterForSave},
    {"RegisterForSavePerCharacter", LuaRegisterForSavePerCharacter},
    {"ReloadUI", LuaReloadUI},
    {"RequestTimePlayed", LuaRequestTimePlayed},
    {"StopMacro", macro_lua::LuaStopMacro},
    {"Stuck", LuaStuck},
    {"UpdateAddOnCPUUsage", LuaUpdateAddOnCPUUsage},
    {"UpdateAddOnMemoryUsage", LuaUpdateAddOnMemoryUsage},
    {"ConsoleAddMessage", LuaConsoleAddMessage},
    {"GetModifiedClickAction", LuaGetModifiedClickAction},
    {"MakeMinigameMove", LuaMakeMinigameMove},
    {"PlayDance", LuaPlayDance},
    {"GetEventCPUUsage", LuaGetEventCPUUsage},
    {"GetFrameCPUUsage", LuaGetFrameCPUUsage},
    {"GetFunctionCPUUsage", LuaGetFunctionCPUUsage},
    {"GetMacroItemIconInfo", macro_lua::LuaGetMacroItemIconInfo},
    {"GetNumDeclensionSets", LuaGetNumDeclensionSets},
    {"SendSystemMessage", LuaSendSystemMessage},
};

}

std::vector<openwow::ui::lua::NativeBindingCatalog>
FrameXmlCoreNativeBindingSources() {
  using openwow::ui::lua::BindingScope;
  using openwow::ui::lua::NativeFunctionCatalog;
  return {
      NativeFunctionCatalog(
          "foundation.time", BindingScope::kShared,
          kWorldTimeSystemBindings),
      NativeFunctionCatalog(
          "runtime.framescript.system", BindingScope::kWorld,
          kSystemLuaBindings),
  };
}

}
